### Criar categoria
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Tecnologia",
  "description": "Notícias sobre tecnologia"
}

### Listar categorias
GET http://localhost:3000/categories


### Deletar categoria
DELETE http://localhost:3000/categories/6ee9dc24-a462-4c50-b199-3da0f9606f6c

